kind: pipeline
name: build
type: docker
volumes:
  - name: go-path
    host:
      path: /srv/go
  - name: go-cache
    host:
      path: /root/.cache/go-build

steps:
  - name: go-build
    image: golang:1.20.4
    commands:
      - cd /serve
      - ls
      - go mod tidy
      - go build -o serve
      - ls
#      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
    volumes:
      - name: go-path
        path: /go
      - name: go-cache
        path: /root/.cache/go-build

