kind: pipeline
type: docker
name: default

volumes:
- name: cache
  host:
    path: /root/.cache/go-build

steps:
  - name: build
    image: golang:1.20.1
    commands:
      - go build
    volumes:
      - name: cache
        path: /root/.cache/go-build

