kind: pipeline
name: build
type: docker
volumes:
  - name: go-pkg
    host:
      path: /root/go
  - name: go-cache
    host:
      path: /root/.cache/go-build


steps:
  - name: go-build
    image: golang:1.20.4
    commands:
      - go mod tidy
      - go build -o serve
      - go env
#      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
    volumes:
      - name: go-pkg
        path: /root/go
      - name: go-cache
        path: /root/.cache/go-build

