kind: pipeline
name: build
type: docker
volumes:
  - name: go-pkg
    host:
      path: /root/go/pkg/mod
  - name: go-cache
    host:
      path: /root/.cache/go-build
  - name: go-save
    host:
      path: /srv/www/serve

steps:
  - name: go-build
    image: golang:1.20.4
    commands:
      - cd serve
      - go mod tidy
      - go build -o serve
      - mv serve /srv/www/serve/serve
    volumes:
      - name: go-pkg
        path: /go/pkg/mod
      - name: go-cache
        path: /root/.cache/go-build
      - name: go-save
        path: /srv/www/serve

kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
   - cd /srv/www/serve
   - rm serve
  volumes:
   - name: go-save
     path: /srv/www/serve

# depends_on:
#   - build
